### ISSUE TITLE
Unify Log Files

### ISSUE THREAD

**Issue by abh3** [lsst/qserv#146]
Currently, the xrootd/cmsd/Ssi infrastructure has an independent log file scheme from the one used by qserv itself. I'm opening this ticket as a discussion point on whether or not we need to unify these and how might unification be implemented and what are the practical implications.

**Comment by ktlim** [comment]
I'd prefer if you discussed this either in JIRA or in community.lsst.org, not here.  We are trying to limit the number of places that need to be searched for discussions.

**Comment by abh3** [comment]
I must have misunderstood Andy's comment. Not a problem.
